export const userStatistics = {
    'balances': {
        'cs.money': { value: 65451, type: 'money' },
        'steam': { value: 5658, type: 'money' },
        'buff.163': { value: 5658, type: 'money' },
        'total balance': { value: 15658, type: 'money' },
    },
    'statistics for today': {
        'transported items': { value: 15, type: 'money' },
        'transported count': { value: 5, type: 'number' },
        'purchased items': { value: 15, type: 'money' },
        'purchased count': { value: 5, type: 'number' },
        'sold items': { value: 25.31, type: 'money' },
        'sold count': { value: 10, type: 'number' },
        'listed items': { value: 18.14, type: 'money' },
        'listed items count': { value: 5, type: 'number' },
        'total profit': { value: 29.31, type: 'money' },
    },
    'statistics for month': {
        'transported items': { value: 15, type: 'money' },
        'transported count': { value: 5, type: 'number' },
        'purchased items': { value: 15, type: 'money' },
        'purchased count': { value: 5, type: 'number' },
        'sold items': { value: 25.31, type: 'money' },
        'sold count': { value: 10, type: 'number' },
        'total profit': { value: 29.31, type: 'money' },
    },
    'statistics for year': {
        'purchased items': { value: 15, type: 'money' },
        'purchased count': { value: 5, type: 'number' },
        'sold items': { value: 25.31, type: 'money' },
        'sold count': { value: 10, type: 'number' },
        'total profit': { value: 29.31, type: 'money' },
    },
};